var mobNo=7620607410;
console.log("mobile no :",mobNo);
console.log("typeof variable mobNo:",typeof mobNo);
var weight=63;
console.log("weight:",weight);
console.log("typeof variable weight:",typeof weight);
var height=5.6;
console.log("height:",height);
console.log("typeof  variable height:",typeof height);
var city="chandrapur";
console.log("city:",city);
console.log("typeof variable city:", typeof city);
var frdName="vivek";
console.log("friend name:",frdName);
console.log("typeof  variable frdName:",typeof frdName);
var sirName="sonule";
console.log("sirname:",sirName);
console.log("typeof variable sirName:",typeof sirName);
var isVeg=true;
console.log("is veg:",isVeg);
console.log("typeof variable isVeg:",typeof isVeg);
var isDeveloper=true;
console.log("is developer:",isDeveloper);
console.log("typeof variable isDeveoper:",typeof isDeveloper);
var isCricPlay=false;
console.log("is cricket player:",isCricPlay);
console.log("typeof variable cricPlay:",typeof isCricPlay);
console.log("null means empty value");
console.log("undefined means variable is declare but value not defined");
